# Generated by Django 5.1.5 on 2025-03-12 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='score',
        ),
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('player', 'Player'), ('admin', 'Admin')], default='player', max_length=10),
        ),
    ]
