# Generated by Django 5.1.5 on 2025-03-12 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
    ]
