# Generated by Django 5.1.5 on 2025-04-09 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_auto_20250312_1524'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamesession',
            name='health',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='gamesession',
            name='items',
            field=models.TextField(default='[]'),
        ),
    ]
